name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup prod dependencies
        run: yarn install
      - name: Deploy infrastructure
        uses: serverless/github-action@v3
        with:
          args: deploy --stage prod --verbose
        env:
          AWS_REGION: eu-central-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          APP_DOMAIN_HOSTED_ZONE: ${{ secrets.APP_DOMAIN_HOSTED_ZONE }}
          APP_DOMAIN: baby-journal.app
      - name: Build app
        run: ./node_modules/.bin/ng build
      - name: Copy files to S3
        env:
          STACK_NAME: BabyTrackerUi-prod
          AWS_REGION: eu-central-1
        run: |
          BUCKET=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query "Stacks[0].Outputs[?OutputKey=='Bucket'].OutputValue" --output=text)
          aws s3 sync dist/baby-tracker-ui s3://$BUCKET
